CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    config_version INTEGER NOT NULL,
    humidity_threshold DOUBLE PRECISION NOT NULL,
    temperature_threshold DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_devices_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT uq_devices_owner UNIQUE (owner_id)
);

CREATE TABLE medication_containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    container_number INTEGER NOT NULL,
    medication_name VARCHAR(150),
    dosage_label VARCHAR(150),
    remaining_pills INTEGER NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    CONSTRAINT fk_containers_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_container UNIQUE (device_id, container_number),
    CONSTRAINT chk_container_number CHECK (container_number BETWEEN 1 AND 5),
    CONSTRAINT chk_remaining_pills CHECK (remaining_pills >= 0)
);

CREATE TABLE medication_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    container_id BIGINT NOT NULL,
    time TIME NOT NULL,
    days_of_week VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT fk_schedules_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_schedules_container FOREIGN KEY (container_id) REFERENCES medication_containers(id) ON DELETE CASCADE
);

CREATE TABLE intake_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    container_number INTEGER NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_intake_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_intake_container_number CHECK (container_number BETWEEN 1 AND 5)
);

CREATE TABLE environment_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    humidity DOUBLE PRECISION NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    risk_status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_environment_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

CREATE INDEX ix_containers_device ON medication_containers(device_id);
CREATE INDEX ix_schedules_device ON medication_schedules(device_id);
CREATE INDEX ix_intake_device_scheduled_at ON intake_records(device_id, scheduled_at);
CREATE INDEX ix_environment_device_recorded_at ON environment_readings(device_id, recorded_at);
