ALTER TABLE devices ADD COLUMN last_known_mqtt_connected BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_rtc_ok BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_sht3x_ok BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_dfplayer_ok BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_sd_card_ok BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_switch_ok BOOLEAN;
ALTER TABLE devices ADD COLUMN last_known_button_pin INTEGER;
ALTER TABLE devices ADD COLUMN last_known_free_heap BIGINT;
ALTER TABLE devices ADD COLUMN last_known_rssi INTEGER;
ALTER TABLE devices ADD COLUMN last_known_firmware_version VARCHAR(60);

ALTER TABLE environment_readings ADD COLUMN event_id VARCHAR(120);
ALTER TABLE environment_readings ADD COLUMN firmware_version VARCHAR(60);
CREATE UNIQUE INDEX IF NOT EXISTS ux_environment_readings_event_id ON environment_readings(device_id, event_id);

ALTER TABLE intake_records ADD COLUMN event_id VARCHAR(120);
ALTER TABLE intake_records ADD COLUMN source VARCHAR(30);
ALTER TABLE intake_records ADD COLUMN button_pin INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS ux_intake_records_event_id ON intake_records(device_id, event_id);

CREATE TABLE device_heartbeats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    event_id VARCHAR(120) NOT NULL,
    rtc_time TIMESTAMP WITH TIME ZONE,
    wifi_connected BOOLEAN,
    mqtt_connected BOOLEAN,
    rtc_ok BOOLEAN,
    sht3x_ok BOOLEAN,
    dfplayer_ok BOOLEAN,
    sd_card_ok BOOLEAN,
    switch_ok BOOLEAN,
    button_pin INTEGER,
    free_heap BIGINT,
    rssi INTEGER,
    device_status VARCHAR(40),
    firmware_version VARCHAR(60),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_device_heartbeats_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_heartbeats_event_id UNIQUE (event_id)
);

CREATE TABLE device_stock_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    event_id VARCHAR(120) NOT NULL,
    container_number INTEGER NOT NULL,
    remaining_pills INTEGER NOT NULL,
    reported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reason VARCHAR(60),
    CONSTRAINT fk_device_stock_events_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT uq_device_stock_events_event_id UNIQUE (event_id),
    CONSTRAINT chk_device_stock_events_container_number CHECK (container_number BETWEEN 1 AND 5),
    CONSTRAINT chk_device_stock_events_remaining_pills CHECK (remaining_pills >= 0)
);

CREATE INDEX ix_device_heartbeats_device_recorded_at ON device_heartbeats(device_id, recorded_at);
CREATE INDEX ix_device_stock_events_device_reported_at ON device_stock_events(device_id, reported_at);
